### ISSUE TITLE
Cannot parse animation: var(--foo)

### ISSUE THREAD

**Issue by nolanlawson** [hookhookun/parse-animation-shorthand#10]
Animation shorthands [can contain CSS custom properties](https://codepen.io/nolanlawson-the-selector/pen/abWqjRW), but this causes an error when parsed.

Repro:

```js
const { parse } = require('@hookun/parse-animation-shorthand')
parse('var(--foo) slidein')
```

Result:

```
$Error: NoIdent: var→(--foo) slidein
    at Object.exports.getCustomIdent (/Users/nlawson/workspace/lwc/node_modules/@hookun/parse-animation-shorthand/lib/getCustomIdent.js:34:11)
    at exports.parseSingleAnimationShorthand (/Users/nlawson/workspace/lwc/node_modules/@hookun/parse-animation-shorthand/lib/parseSingleAnimationShorthand.js:52:53)
    at Array.map (<anonymous>)
    at exports.parseAnimationShorthand (/Users/nlawson/workspace/lwc/node_modules/@hookun/parse-animation-shorthand/lib/parseAnimationShorthand.js:4:63)
    at Object.<anonymous> (/Users/nlawson/workspace/lwc/test.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'NoIdent'
}

```

**Comment by hookhookun** [comment]
Thank you. I had overlooked that. However, since the type of the variable is not known when parsing, so the current version cannot support variables. I will try to fix it, but it will take some time.

The following are my notes.

1. To solve this problem, we need to take the type of the variables.
2. What is the representation of types in CSS?
3. There is a syntax to declare the type of variables: https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule

Example of a type declaration object:

```typescript
{
  foo: '<number>',
  bar: '<custom-ident>',
}
```

**Comment by hookhookun** [comment]
Note: I am currently working on a way to parse this syntax.

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#custom_property_fallback_values
> ### Custom property fallback values
> Using the var() function, you can define multiple fallback values when the given variable is not yet defined.
> ```css
> .three {
>   background-color: var(--my-var, var(--my-background, pink));
>                     /* pink if --my-var and --my-background are not defined */
> }
> ```
>
